### ISSUE TITLE
Colors not working on Emacs 26.0.50 (master)

### ISSUE THREAD

**Issue by dieggsy** [kuanyui/tldr.el#18]
You can see the face is themed, but not showing up. The default colors don't show up either...

![2017-05-27_11 07 04](https://cloud.githubusercontent.com/assets/9020453/26522412/11ae3b10-42ce-11e7-8914-aabd94767928.png)

**Comment by dieggsy** [comment]
Er, interestingly enough, can't reproduce. Don't know what that was about.

**Comment by franburstall** [comment]
I am having this issue too with emacs 26.1 (and zenburn theme, if that is relevant).  This used to work fine but I don't use `tldr-mode` often enough to accurately pin-point when it started to fail.

**Comment by franburstall** [comment]
Problem solved: `rainbow-mode` interacts badly with `tldr-mode` and I had `rainbow-mode` in `help-mode-hook` which `tldr-mode` calls.
