### ISSUE TITLE
Missing pages of other folders than common

### ISSUE THREAD

**Issue by technician77** [kuanyui/tldr.el#19]
Hello kuanyui,

I came across your package since abo-abo recommended it on reddit, which is quite an honour I think. Since I'm a network guy I was looking for certain commands, but it turns out that they are missing at least in the search. The shell command that updates/inflates the pages seems to be successful though.

It seems that the search is only conducted in the common folder and not the others.

```
inflating: z:/home/myuser/.emacs.d/tldr-master/pages/linux/ip.md  
inflating: z:/home/myuser/.emacs.d/tldr-master/pages/linux/iptables.md
```  

![image](https://cloud.githubusercontent.com/assets/18722291/26554070/c82f9fac-448e-11e7-880e-f83c3ad117f1.png)

With kind regards
tech77

**Comment by kuanyui** [comment]
What's your OS?

**Comment by technician77** [comment]
Win7-64

**Comment by kuanyui** [comment]
OK, in the beginning, I supposed that Windows users needn't manuals for UNIX tools until I started to use Windows + MSYS2 months earlier so I exclude them. I will fix it.

**Comment by technician77** [comment]
Thanks, I mainly work on linux machines remotely. Even the osx commands might come in handy when I might need to check something on a customer machine. Macs are becoming increasingly poplular even in corporate environments.

**Comment by kuanyui** [comment]
Now you can customize like this:
```lisp
(setq tldr-enabled-categories '("common" "linux" "osx" "sunos"))
```
Sorry for so late reply.
