### ISSUE TITLE
Feature Request: Category Filter

### ISSUE THREAD

**Issue by technician77** [kuanyui/tldr.el#20]
Thanks for implementing category selections, this works great. Now I can see at least the commands I want (without fiddling with the files).

I can't help myself but now I must ask for filters, and a default setting for them. My idea of the workflow would be this:
1. Using the category variable I set which categories I need.
2. Using a filter default setting I set the categories I want to see when starting tldr (or tldr-mode)
3. Using a command (in tldr-mode maybe a key) I define the filters I need now different from the default filter setting

Example for my personal needs:
1. I don't think I need sunos, so I would remove it at this point
2. In normal cases I would need only common and linux
3. Let's say I need to check the ip/routes or something like that on OSX, because a customer owns a machine like that. In this case I would like to see only the OSX commands (and switch filters back after I found what I need)

I don't know how you think about filters like these, ultimatively the category selection would be sufficient, but I think a filter would be quicker. Using the category selection variable for that feels more like a workaround.

Finally , since I'm not a coder I can't grasp how much work it would be to implement them. So even if you agree about the usefulness I would understand if you don't implement them because it takes too much effort.

**Comment by kuanyui** [comment]
You can rely on Emacs' "Lisp environment": just define your functions to look up tldr within different categories. For example, to look up in all categories without changing `tldr-enabled-categories` globally:

```lisp
(defun tldr-my-all ()
  (interactive)
  (let ((tldr-enabled-categories '("common" "linux" "osx" "sunos")))
    (tldr)))
```

**Comment by technician77** [comment]
This is awesome. Thank you so much. Yeah, I have no coding knowlege, so I couldn't have come up with this myself. I have configured all the functions I needed based on your example, now everything works exactly as needed. Maybe it's also useful for other users.

**Comment by kuanyui** [comment]
Feel free, that is OK unless you want to become a Emacs guru.

2017/07/03 午後6:54 "technician77" <notifications@github.com>:
