### ISSUE TITLE
support private page repo

### ISSUE THREAD

**Issue by driftcrow** [kuanyui/tldr.el#24]
sometimes I want create page
but content is private or not important for others, then can't be merged into
the main repo.   support private page repo with a quick create page func can make it more practical.

**Comment by kuanyui** [comment]
W...wh...wrrrrrry what?!
Jojo! What is this bizarre usage scenario? Can you elaborate it? Why not, for example, use org-mode to store your notes?

**Comment by driftcrow** [comment]
maybe org-mode note is the right way, just need a tldr likes front view.

**Comment by kuanyui** [comment]
I don't think this feature is useful to few people. And this package is designed for tldr pages, instead of personal wiki.
If you like, you can fork this package to implement it. The mechanism of how `tldr` works is very simple.
