### ISSUE TITLE
Support for translated pages

### ISSUE THREAD

**Issue by arunisaac** [kuanyui/tldr.el#30]
Hi,

This is a feature request. Could you implement support for the new language and translations support in the client specification?

https://github.com/tldr-pages/tldr/blob/master/CLIENT-SPECIFICATION.md

Thank you!

**Comment by kuanyui** [comment]
Sorry, have no time currently. Feel free to make a PR if willing!

**Comment by arunisaac** [comment]
Sure, I understand. I will send a PR.
