### ISSUE TITLE
Wish: If in scratch buffer, replace the buffer

### ISSUE THREAD

**Issue by ArneBab** [kuanyui/tldr.el#34]
If I start emacs as standalone TLDR client with `emacs -q -e tldr` it starts with the *scratch* buffer and tldr only occupying half the window. It would be useful if tldr could just replace the buffer in this case. More precisely:

if
```
(and
 (equal  "*scratch*" (buffer-name))
 (window-full-height-p)
 (window-full-width-p)
 (not (buffer-modified-p)))
```
then open tldr as the only window in the frame.

**Comment by kuanyui** [comment]
I estimate your using scenario, I don't think this is a universal behavior
which can satisfy everyone, I even think this may make other user confused
instead. I recommend you to write a hook function for yourself. For example:

```lisp
(defun my-tldr-hook-fn ()
  (let ((wins (window-list)))
    (if (and (eq (length wins) 2)
       (some #'identity (mapcar
             (lambda (w) (equal "*tldr*" (buffer-name (window-buffer w))))
             (window-list))))
  (delete-other-windows))))

(add-hook 'tldr-mode-hook 'my-tldr-hook-fn)
```

2021年9月7日(火) 22:27 Arne Babenhauserheide ***@***.***>:

**Comment by kuanyui** [comment]
I estimate your using scenario, I don't think this is a universal behavior
which can satisfy everyone, I even think this may make other user confused
instead. I recommend you to write a hook function for yourself. For example:

```lisp
(defun my-tldr-hook-fn ()
  (let ((wins (window-list)))
    (if (and (eq (length wins) 2)
       (some #'identity (mapcar
             (lambda (w) (equal "*tldr*" (buffer-name (window-buffer w))))
             (window-list))))
  (delete-other-windows))))

(add-hook 'tldr-mode-hook 'my-tldr-hook-fn)
```

**Comment by ArneBab** [comment]
Thank you for that hint. My scenario is for making emacs usable as tldr client for people who do not live in Emacs.

My scenario is that I want to create an executable that provides tldr from emacs.

The hook is a nice idea, and it can be even simpler: 

`emacs --exec "(add-hook 'tldr-mode-hook 'delete-other-windows)" -q -e tldr`

This does what I want.
