### ISSUE TITLE
Pages for "[" and "[[" don't work

### ISSUE THREAD

**Issue by david-jennings** [kuanyui/tldr.el#36]
[[](https://github.com/tldr-pages/tldr/blob/main/pages/common/%5B.md) and [[[](https://github.com/tldr-pages/tldr/blob/main/pages/common/%5B%5B.md) are both supported pages at [tldr pages](https://github.com/tldr-pages/tldr/tree/main/pages/common).
When searching for them in the linux client we get the error `Invalid regexp: "Unmatched [ or [^"`.
Quoting with `"` or `\` doesn't work either.

**Comment by slayer152** [comment]
Created a PR with the fix - needed to call `regexp-quote` on `command` variable in the last conditional branch in`tldr-render-markdown`.
