### ISSUE TITLE
tldr hangs indefinitely

### ISSUE THREAD

**Issue by sebnyberg** [kuanyui/tldr.el#37]
I'm using Doom Emacs

```bash
GNU Emacs     v27.1
Doom core     v3.0.0-pre
Doom modules  v22.09.0-pre
```

I installed tldr using the regular procedure `(package! tldr)`.

Running `M-x tldr-update-docs` works just fine.

Running `M-x tldr` makes Emacs hang indefinitely.

Since I know nearly nothing about Emacs, Doom Emacs or Lisp, I turned to `opensnoop` and `strace -f` for clues and found these two syscalls:

```bash
renameat2(AT_FDCWD, "/home/seb/.emacs.d/.local/cachetldr-main", AT_FDCWD, "/home/seb/.emacs.d/.local/cache/tldr/", RENAME_NOREPLACE) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/home/seb/.emacs.d/.local/cache/tldr/", 0x7ffe2d6596d0, 0) = -1 ENOENT (No such file or directory)
```

It appears that the source path is missing a `/`, i.e. `cachetldr-main` should be `cache/tldr-main`.

As a temporary fix, you can symlink the directory

```bash
ln -s ~/.emacs.d/.local/cache/tldr-main ~/.emacs.d/.local/cache/tldr
```

**Comment by kuanyui** [comment]
Please consider to provide a PR because I cannot reproduce in my environment. (I don't use Doom)

**Comment by sebnyberg** [comment]
I'm not proficient enough to contribute with a PR so I'll close this. Thank you for your consideration.
