### ISSUE TITLE
Adding a description/annotation for each command

### ISSUE THREAD

**Issue by slayer152** [kuanyui/tldr.el#38]
Hello, I think it'd be helpful if the completing-read interface provides a description of each command. Here's an implementation to achieve this.

```
(defun tldr-completion-annotation(command)
"Provide description for command COMMAND."
  (when-let ((file-path (tldr-get-file-path-from-command-name command))
             (max-len-command-name (apply #'max (mapcar #'length (tldr-get-commands-list)))))
    (with-temp-buffer
      (insert-file-contents file-path)
      (and (search-forward "> " (point-max) t 1)
           (concat (make-string (- max-len-command-name (length command)) ? )
                          " -- " 
                         (buffer-substring-no-properties (point) (line-end-position)))))))


;; Change let -> let* and add (completion-extra-properties '(:annotation-function tldr-completion-annotation))
(defun tldr (&optional cmd)
  "Lookup TLDR docs."
...
(let* ((completion-extra-properties '(:annotation-function tldr-completion-annotation))
          (command (or cmd
                       (completing-read "TLDR: " (tldr-get-commands-list) nil t
                                        (when tldr-use-word-at-point (current-word))))))
...)
```

Here's the result:
With emacs -Q
<img width="1512" alt="Screen Shot 2022-11-08 at 4 24 09 PM" src="https://user-images.githubusercontent.com/71155182/200705696-e6778922-e31f-4a0e-b760-26da9a7caa95.png">

With `vertico' and `marginalia'
<img width="1512" alt="Screen Shot 2022-11-08 at 4 26 54 PM" src="https://user-images.githubusercontent.com/71155182/200705968-41eb6a27-c0a1-410e-8812-bc70c2f0365c.png">

**Comment by kuanyui** [comment]
Looks cool! But I don't know if this impact performance, can you create a PR and make a variable/option to enable this? thanks!

**Comment by slayer152** [comment]
> Looks cool! But I don't know if this impact performance, can you create a PR and make a variable/option to enable this? thanks!

Sure, will do.

**Comment by slayer152** [comment]
I've set user-option `tldr-enable-annotations` by default to `t` - No perf impact was seen on on two machines: `GNU Emacs 28.2 (build 2, aarch64-apple-darwin21.3.0)` and `GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 2.24.23)`.

We can set it to `nil` by default if you feel it's safer.
